### ISSUE TITLE
[BUG] module 'idaapi' has no attribute 'compiled_binpat_vec_t'

### ISSUE THREAD

**Issue by neobenedict** [VoidSec/DriverBuddyReloaded#27]
```Failed while executing plugin_t.run():
Traceback (most recent call last):
  File "C:/Program Files/IDA 7.0/plugins/DriverBuddyReloaded.py", line 465, in run
    driver_type = utils.get_driver_id(driver_entry_addr, log_file)
  File "C:/Program Files/IDA 7.0/plugins\DriverBuddyReloaded\utils.py", line 209, in get_driver_id
    populate_wdf()
  File "C:/Program Files/IDA 7.0/plugins\DriverBuddyReloaded\wdf.py", line 102, in populate_wdf
    binpat = idaapi.compiled_binpat_vec_t()
AttributeError: module 'idaapi' has no attribute 'compiled_binpat_vec_t'
```

Version 7.5.201028 Windows x64 (64-bit address size)

7.6 minimum required?

**Comment by VoidSec** [comment]
It was tested starting from IDA 7.6 but shouldn't be required. If you can share the file making it crash (privately?), Ill try to determine the cause and fix it. Regards

**Comment by neobenedict** [comment]
3.8.3

I'll try a later version of IDA in a few days.

**Comment by zeze-zeze** [comment]
Same issue in IDA 7.5 and Python 3.9.4

**Comment by VoidSec** [comment]
would you mind sharing the driver causing the error?

**Comment by zeze-zeze** [comment]
Sure, it is not rare to find such driver.
[NVSWCFilter64.zip](https://github.com/VoidSec/DriverBuddyReloaded/files/9677002/NVSWCFilter64.zip)

**Comment by rjt-gupta** [comment]
Sorry to remention, but Im facing this on latest release. However, I'm on IDA v7.2. Any resolution for this?

**Comment by VoidSec** [comment]
@rjt-gupta would you mind sharing the driver causing the error? You can send me an email at voidsec[at]voidsec.com if you'd like to keep it private.

**Comment by VoidSec** [comment]
@HongThatCong thank you very much for pointing that out! I'll update the readme in order to reflect that requirement

**Comment by rjt-gupta** [comment]
@HongThatCong @VoidSec Thanks for the clarification. Unfortunately, I can't share the driver since its proprietary. But, please let me know if there is a workaround for this issue for IDA < v7.5

**Comment by HongThatCong** [comment]
Yes, @VoidSec can rewrite the binary search function with code in picture above and this picture:
![image](https://github.com/VoidSec/DriverBuddyReloaded/assets/67528122/32502f3d-b763-4eb1-9ada-78d7c1dcb974)

**Comment by rjt-gupta** [comment]
@VoidSec Do you plan to fix this anytime soon?

**Comment by VoidSec** [comment]
I'll probably take some time next week to patch some of these bugs.
